# Generated by Django 3.1.2 on 2020-10-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('chat_hour', models.IntegerField()),
                ('chat_minute', models.IntegerField()),
                ('send_to', models.CharField(choices=[('공식 단톡', 'SSAFY 4기 서울 3반(A반)'), ('잡담방', '#잡담방 SSAFY 4기 3(A)반'), ('테스트', '구본혁'), ('스터디', '챗봇 스터디')], default='테스트', max_length=50)),
            ],
        ),
    ]
