# Generated by Django 3.1.2 on 2020-10-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatinfo',
            name='send_to',
            field=models.CharField(choices=[('SSAFY 4기 서울 3반(A반)', 'SSAFY 4기 서울 3반(A반)'), ('#잡담방 SSAFY 4기 3(A)반', '#잡담방 SSAFY 4기 3(A)반'), ('구본혁', '구본혁'), ('챗봇 스터디', '챗봇 스터디')], default='구본혁', max_length=50),
        ),
    ]
